# Example Usage

In [2]:
# Keep track of runtime which will be printed at the end of this notebook
import time
start = time.time()

In [3]:
# Library imports
import pathlib

import numpy as np
import pandas as pd

# Local modules
import functions as f

In [4]:
# The list of geographies to run on. To add any additional geography such as "mgra", simply add it 
# to the list below. 
# NOTE: Including "mgra" may result in extremely long processing times. As far as I can tell, this 
# is due to SQL Server taking an extremely long time to process the age_sex_ethnicity table at the
# mgra level. When running on Eric's Surface laptop, simply getting/saving the age_ethnicity and
# age_sex_ethnicity tables at the mgra level took about 20 minutes each.
GEOGRAPHIES = ["region", "jurisdiction", "cpa", "mgra"]

# The estimates tables to run on. The tables are split up into three different variables
# EST_TABLES contains Estimates tables where the key columns are ONLY geography name and year
# AGE_SEX_ETHNICITY contains Estimates tables where key columns contain additional information such
# as age category or ethnicity category
# CONSOLIDATED is the name of the consolidated file
EST_TABLES = ['age', 'ethnicity', 'household_income', 'households', 'housing', 'population', 'sex']
AGE_SEX_ETHNICITY = ["age_ethnicity", "age_sex_ethnicity"]
CONSOLIDATED = ["consolidated"]

# The Estimates/DOF vintages to run on. Checks are run on the NEW_VINTAGE by default. OLD_VINTAGE is
# only used in the creation of diff files, which contain NEW_VINTAGE - OLD_VINTAGE. DOF_VINTAGE is
# used for downloading DOF data, and comparing region level population values in Check 6
NEW_VINTAGE = "2021_01"
OLD_VINTAGE = "2020_06"
DOF_VINTAGE = "2021_07_14"

# Default locations where files should be saved to and loaded from.
# NOTE: These folders are created by the save function, no need to do so yourself.
RAW_FOLDER = pathlib.Path("./data/raw_data/")
DIFF_FOLDER = pathlib.Path("./data/diff/")
PROP_FOLDER = pathlib.Path("./data/proportion/")
OUTPUTS_FOLDER = pathlib.Path("./data/outputs/")

In [5]:
# Import the module that allows us to create tables
import generate_tables as gt

### Creating Estimates Tables (generate_tables.EstimatesTables)

In [17]:
# Creating individual files (one file per unique geography and Estimate table)
# I stopped after 37 minutes
# "_ =" to suppress output
_ = gt.EstimatesTables().individual(
        est_vintage=NEW_VINTAGE,
        geo_list=GEOGRAPHIES,
        est_table_list=EST_TABLES + AGE_SEX_ETHNICITY,
        save=True,
        save_folder=RAW_FOLDER,
        overwrite=False)

Exception during reset or similar
Traceback (most recent call last):
  File "c:\Users\cra\OneDrive - San Diego Association of Governments\QA_Repository\2022\Estimates_QC_Automation\generate_tables.py", line 470, in individual
    f.load(save_folder, est_vintage, geo, est_table_name)
  File "c:\Users\cra\OneDrive - San Diego Association of Governments\QA_Repository\2022\Estimates_QC_Automation\functions.py", line 124, in load
    raise FileNotFoundError(textwrap.dedent(f"""\
FileNotFoundError: No files found for the glob string "QA_2021_01_mgra_age_sex_ethnicity.*" in the folder data\raw_data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\pymssql\_pymssql.pyx", line 559, in pymssql._pymssql.Cursor.fetchall
  File "src\pymssql\_pymssql.pyx", line 510, in pymssql._pymssql.Cursor.getrow
  File "src\pymssql\_mssql.pyx", line 468, in pymssql._mssql.MSSQLRowIterator.__next__
  File "src\pymssql\_mssql.pyx", line 1199, in pymssql._mssql.MSSQLConnection.fetch_next_row
  File "src\pymssql\_mssql.pyx", line 1786, in pymssql._mssql.check_cancel_and_raise
  File "src\pymssql\_mssql.pyx", line 1832, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20004, b'DB-Lib error message 20004, severity 9:\nRead from the server failed\nNet-Lib error during Unknown error (10054)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
  File "src\pymssql\_pymssql.pyx", line 565, in pymssql._pymssql.Cursor.fetchall
pymssql._pymssql.OperationalError: (20004, b'DB-Lib error message 20004, severity 9:\nRead from the server failed\nNet-Lib error during Unknown error (10054)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 972, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "src\pymssql\_pymssql.pyx", line 316, in pymssql._pymssql.Connection.rollback
  File "src\pymssql\_pymssql.pyx", line 300, in pymssql._pymssql.Connection.rollback
  File "src\pymssql\_mssql.pyx", line 1053, in pymssql._mssql.MSSQLConnection.execute_non_query
  File "src\pymssql\_mssql.pyx", line 1074, in pymssql._mssql.MSSQLConnection.execute_non_query
  File "src\pymssql\_mssql.pyx", line 1229, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src\pymssql\_mssql.pyx", line 778, in pymssql._mssql.MSSQLConnection.cancel
  File "src\pymssql\_mssql.pyx", line 1837, in pymssql._mssql.assert_connected
pymssql._mssql.MSSQLDriverException: Not connected to any MS SQL server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2027, in _handle_dbapi_exception
    self._autorollback()
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 84, in __exit__
    compat.raise_(value, with_traceback=traceback)
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2027, in _handle_dbapi_exception
    self._autorollback()
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1102, in _autorollback
    self._rollback_impl()
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 974, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1934, in _handle_dbapi_exception
    util.raise_(
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 972, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "src\pymssql\_pymssql.pyx", line 316, in pymssql._pymssql.Connection.rollback
  File "src\pymssql\_pymssql.pyx", line 300, in pymssql._pymssql.Connection.rollback
  File "src\pymssql\_mssql.pyx", line 1053, in pymssql._mssql.MSSQLConnection.execute_non_query
  File "src\pymssql\_mssql.pyx", line 1074, in pymssql._mssql.MSSQLConnection.execute_non_query
  File "src\pymssql\_mssql.pyx", line 1229, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src\pymssql\_mssql.pyx", line 778, in pymssql._mssql.MSSQLConnection.cancel
  File "src\pymssql\_mssql.pyx", line 1837, in pymssql._mssql.assert_connected
sqlalchemy.exc.DBAPIError: (pymssql._mssql.MSSQLDriverException) Not connected to any MS SQL server
(Background on this error at: https://sqlalche.me/e/14/dbapi)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Users\cra\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "src\pymssql\_pymssql.pyx", line 316, in pymssql._pymssql.Connection.rollback
  File "src\pymssql\_pymssql.pyx", line 300, in pymssql._pymssql.Connection.rollback
  File "src\pymssql\_mssql.pyx", line 1053, in pymssql._mssql.MSSQLConnection.execute_non_query
  File "src\pymssql\_mssql.pyx", line 1074, in pymssql._mssql.MSSQLConnection.execute_non_query
  File "src\pymssql\_mssql.pyx", line 1229, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src\pymssql\_mssql.pyx", line 778, in pymssql._mssql.MSSQLConnection.cancel
  File "src\pymssql\_mssql.pyx", line 1837, in pymssql._mssql.assert_connected
pymssql._mssql.MSSQLDriverException: Not connected to any MS SQL server

DBAPIError: (pymssql._mssql.MSSQLDriverException) Not connected to any MS SQL server
(Background on this error at: https://sqlalche.me/e/14/dbapi)

In [6]:
# Creating consolidated files (one file per geography, contains all requested tables)
# NOTE: The additional parameter get_from_file=True allows the function to pull data from already
# downloaded Estimates tables, instead of re-downloading and holding in memory
_ = gt.EstimatesTables().consolidate(
        est_vintage=NEW_VINTAGE, 
        geo_list=GEOGRAPHIES,
        est_table_list=EST_TABLES, 
        get_from_file=True,
        raw_folder=RAW_FOLDER,
        save=True,
        save_folder=RAW_FOLDER)

### Creating DOF Data Files (generate_tables.CA_DOF)

In [8]:
# Creating DOF data files:
# 1. Region level population in each year
# 2. Region level population in each year broken down by age/sex/ethnicity
gt.CA_DOF().get_CA_DOF_region_pop(
    dof_vintage=DOF_VINTAGE, 
    save_folder=RAW_FOLDER)

### Creating Diff Files (generate_tables.DiffFiles)

In [9]:
# First create consolidated and individual files using the same parameters as before but with 
# the OLD_VINTAGE instead of the NEW_VINTAGE
_ = gt.EstimatesTables().individual(
        est_vintage=OLD_VINTAGE,
        geo_list=GEOGRAPHIES,
        est_table_list=EST_TABLES + AGE_SEX_ETHNICITY,
        save=True,
        save_folder=RAW_FOLDER,
        overwrite=False)
_ = gt.EstimatesTables().consolidate(
        est_vintage=OLD_VINTAGE, 
        geo_list=GEOGRAPHIES,
        est_table_list=EST_TABLES, 
        get_from_file=True,
        raw_folder=RAW_FOLDER,
        save=True,
        save_folder=RAW_FOLDER)

In [10]:
# Create diff files 
# NOTE: This will output xlsx files with sheets containing OLD_VINTAGE data, NEW_VINTAGE data, and
# NEW_VINTAGE-OLD_VINTAGE data. This is NOT percent difference, but numeric difference
# NOTE: Because of the way that the diff files are created, python is required to hold essentially
# three full tables in memory at the same time. For the "mgra" level and large tables such as 
# consolidated or age_sex_ethnicity, these result in a lack of memory and impossibly long run times.
# "mgra" is thus removed from diff files
NO_MGRA = GEOGRAPHIES.copy()
NO_MGRA.remove("mgra")
_ = gt.DiffFiles().create_diff_tables(
        old_vintage=OLD_VINTAGE, 
        new_vintage=NEW_VINTAGE, 
        geo_list=NO_MGRA,
        est_table_list=EST_TABLES + CONSOLIDATED + AGE_SEX_ETHNICITY,
        raw_data_folder=RAW_FOLDER,
        save=True,
        save_folder=DIFF_FOLDER)

### Creating Proportion Files (generate_tables.ProportionFiles)

In [11]:
# Create proportion files for estimates tables
gt.ProportionFiles().create_est_proportion_tables( 
    est_vintage=NEW_VINTAGE, 
    geo_list=['region'],
    est_table_list=['age', "sex", 'ethnicity', 'household_income', 'age_ethnicity', 'age_sex_ethnicity'],
    raw_data_folder=RAW_FOLDER,
    save=True,
    save_folder=PROP_FOLDER)

In [12]:
# Create proportion files for DOF tables
gt.ProportionFiles().create_DOF_proportion_table(
    DOF_vintage=DOF_VINTAGE,
    raw_data_folder=RAW_FOLDER,
    save=True,
    save_folder=PROP_FOLDER)

## Run Checks

In [13]:
# Import the module that allows us to run checks
import perform_checks as pc

### Run Check 1

In [14]:
# Run internal consistency checks by geography level
# NOTE: Due to a limitation of the function, "region" cannot be included in the input geo_list
# BUG: If new geographies were added to GEOGRAPHIES, make sure that aggregation instructions are
# updated in the variable InternalConsistency()._geography_aggregation. For more details on how,
# see the class docstring
NO_REGION = GEOGRAPHIES.copy()
NO_REGION.remove("region")
pc.InternalConsistency().check_geography_aggregations(
    vintage=NEW_VINTAGE,
    geo_list=NO_REGION,
    est_table=CONSOLIDATED[0],
    raw_folder=RAW_FOLDER,  
    save=True,
    save_location=OUTPUTS_FOLDER)

Running Check 1: Check aggregated values between geography levels
Aggregating jurisdiction level data to region and comparing with region csv file
No errors

Aggregating cpa level data to jurisdiction and comparing with jurisdiction csv file
CPA cannot be aggregated

Aggregating cpa level data to region and comparing with region csv file
CPA cannot be aggregated

Aggregating mgra level data to cpa and comparing with cpa csv file
CPA cannot be aggregated

Aggregating mgra level data to jurisdiction and comparing with jurisdiction csv file
MGRA cannot be aggregated to jurisdiction due to errors in MGRA 13
If Estimates 2021_01 is not using MGRA 13, code needs to be updated

Aggregating mgra level data to region and comparing with region csv file
No errors

In [15]:
# Run internal consistency checks between Estimates tables
# See function signature for the meaning of "est_table_types"
pc.InternalConsistency().check_internal_aggregations(
        vintage=NEW_VINTAGE, 
        geo_list=GEOGRAPHIES,
        est_table_types=["population", "households"],
        raw_folder=RAW_FOLDER,
        save=True,
        save_location=OUTPUTS_FOLDER)

Running Check 1: Check aggregated values between Estimates tables
Checking Estimates tables with population values at the region level
No errors

Checking Estimates tables with population values at the jurisdiction level
No errors

Checking Estimates tables with population values at the cpa level
No errors

Checking Estimates tables with population values at the mgra level
No errors

Checking Estimates tables with households values at the region level
No errors

Checking Estimates tables with households values at the jurisdiction level
No errors

Checking Estimates tables with households values at the cpa level
No errors

Checking Estimates tables with households values at the mgra level
No errors

### Run Check 2

In [16]:
# Run spot nulls check
# NOTE: Every table in that is combined into CONSOLIDATED is already represented in EST_TABLES
pc.NullValues().spot_nulls(
    vintage=NEW_VINTAGE, 
    geo_list=GEOGRAPHIES, 
    est_table_list=EST_TABLES + AGE_SEX_ETHNICITY, 
    raw_folder=RAW_FOLDER, 
    save=True,
    save_location=OUTPUTS_FOLDER)

Running Check 2: Spot Nulls
Checking QA_2021_01_region_age.
No errors

Checking QA_2021_01_region_ethnicity.
No errors

Checking QA_2021_01_region_household_income.
No errors

Checking QA_2021_01_region_households.
No errors

Checking QA_2021_01_region_housing.
No errors

Checking QA_2021_01_region_population.
No errors

Checking QA_2021_01_region_sex.
No errors

Checking QA_2021_01_region_age_ethnicity.
No errors

Checking QA_2021_01_region_age_sex_ethnicity.
No errors

Checking QA_2021_01_jurisdiction_age.
No errors

Checking QA_2021_01_jurisdiction_ethnicity.
No errors

Checking QA_2021_01_jurisdiction_household_income.
No errors

Checking QA_2021_01_jurisdiction_households.
No errors

Checking QA_2021_01_jurisdiction_housing.
No errors

Checking QA_2021_01_jurisdiction_population.
No errors

Checking QA_2021_01_jurisdiction_sex.
No errors

Checking QA_2021_01_jurisdiction_age_ethnicity.
No errors

Checking QA_2021_01_jurisdiction_age_sex_ethnicity.
No errors

Checking QA_2021_01_cpa_age.
No errors

Checking QA_2021_01_cpa_ethnicity.
No errors

Checking QA_2021_01_cpa_household_income.
No errors

Checking QA_2021_01_cpa_households.
No errors

Checking QA_2021_01_cpa_housing.
No errors

Checking QA_2021_01_cpa_population.
No errors

Checking QA_2021_01_cpa_sex.
No errors

Checking QA_2021_01_cpa_age_ethnicity.
No errors

Checking QA_2021_01_cpa_age_sex_ethnicity.
No errors

Checking QA_2021_01_mgra_age.
No errors

Checking QA_2021_01_mgra_ethnicity.
No errors

Checking QA_2021_01_mgra_household_income.
No errors

Checking QA_2021_01_mgra_households.
No errors

Checking QA_2021_01_mgra_housing.
No errors

Checking QA_2021_01_mgra_population.
No errors

Checking QA_2021_01_mgra_sex.
No errors

Checking QA_2021_01_mgra_age_ethnicity.
No errors

Checking QA_2021_01_mgra_age_sex_ethnicity.

FileNotFoundError: No files found for the glob string "QA_2021_01_mgra_age_sex_ethnicity.*" in the folder data\raw_data

In [ ]:
# Run spot missing geographies/years
# Add on "mgra" geography to this test if missing from the geography list
pc.NullValues().spot_missing_values(
    vintage=NEW_VINTAGE, 
    geo_list=GEOGRAPHIES + ["mgra"],
    est_table_list=EST_TABLES,
    raw_folder=RAW_FOLDER,
    save=True,
    save_location=OUTPUTS_FOLDER)

Running Check 2: Spot Missing Geographies/Years
Checking QA_2021_01_region_age.
No Errors

Checking QA_2021_01_region_ethnicity.
No Errors

Checking QA_2021_01_region_household_income.
No Errors

Checking QA_2021_01_region_households.
No Errors

Checking QA_2021_01_region_housing.
No Errors

Checking QA_2021_01_region_population.
No Errors

Checking QA_2021_01_region_sex.
No Errors

Checking QA_2021_01_jurisdiction_age.
No Errors

Checking QA_2021_01_jurisdiction_ethnicity.
No Errors

Checking QA_2021_01_jurisdiction_household_income.
No Errors

Checking QA_2021_01_jurisdiction_households.
No Errors

Checking QA_2021_01_jurisdiction_housing.
No Errors

Checking QA_2021_01_jurisdiction_population.
No Errors

Checking QA_2021_01_jurisdiction_sex.
No Errors

Checking QA_2021_01_cpa_age.
No Errors

Checking QA_2021_01_cpa_ethnicity.
No Errors

Checking QA_2021_01_cpa_household_income.
No Errors

Checking QA_2021_01_cpa_households.
No Errors

Checking QA_2021_01_cpa_housing.
No Errors

Checking QA_2021_01_cpa_population.
No Errors

Checking QA_2021_01_cpa_sex.
No Errors

Checking QA_2021_01_mgra_age.
No Errors

Checking QA_2021_01_mgra_ethnicity.
No Errors

Checking QA_2021_01_mgra_household_income.
No Errors

Checking QA_2021_01_mgra_households.
No Errors

Checking QA_2021_01_mgra_housing.
No Errors

Checking QA_2021_01_mgra_population.
No Errors

Checking QA_2021_01_mgra_sex.
No Errors

Checking QA_2021_01_mgra_age.
No Errors

Checking QA_2021_01_mgra_ethnicity.
No Errors

Checking QA_2021_01_mgra_household_income.
No Errors

Checking QA_2021_01_mgra_households.
No Errors

Checking QA_2021_01_mgra_housing.
No Errors

Checking QA_2021_01_mgra_population.
No Errors

Checking QA_2021_01_mgra_sex.
No Errors

### Run Check 3

In [ ]:
# Run checks that between Estimates vintages, values do not change by too much
# NOTE: different geography levels have different parameters, as smaller populations tend to have
# more variability.
if("region" in GEOGRAPHIES):
    pc.VintageComparisons().vintage_change(
        p_threshold=2,
        n_threshold=500,
        old_vintage=OLD_VINTAGE,
        new_vintage=NEW_VINTAGE,
        geo_list=["region"],
        est_table_list=EST_TABLES + AGE_SEX_ETHNICITY,
        diff_data_folder=DIFF_FOLDER,
        save=True,
        outputs_folder=OUTPUTS_FOLDER)

Running check 3: Vintage Comparison
Checking between 2020_06 and 2021_01

Checking the age Estimates table at the region level
No errors

Checking the ethnicity Estimates table at the region level
No errors

Checking the household_income Estimates table at the region level
No errors

Checking the households Estimates table at the region level
No errors

Checking the housing Estimates table at the region level
Errors have occurred on the following rows:
Output is too large to print, see output file.

Checking the population Estimates table at the region level
No errors

Checking the sex Estimates table at the region level
No errors

Checking the age_ethnicity Estimates table at the region level
No errors

Checking the age_sex_ethnicity Estimates table at the region level
No errors

In [ ]:
if("jurisdiction" in GEOGRAPHIES):
    pc.VintageComparisons().vintage_change(
        p_threshold=5,
        n_threshold=500,
        old_vintage=OLD_VINTAGE,
        new_vintage=NEW_VINTAGE,
        geo_list=["jurisdiction"],
        est_table_list=EST_TABLES + AGE_SEX_ETHNICITY,
        diff_data_folder=DIFF_FOLDER,
        save=True,
        outputs_folder=OUTPUTS_FOLDER)

Running check 3: Vintage Comparison
Checking between 2020_06 and 2021_01

Checking the age Estimates table at the jurisdiction level
No errors

Checking the ethnicity Estimates table at the jurisdiction level
Errors have occurred on the following rows:
Output is too large to print, see output file.

Checking the household_income Estimates table at the jurisdiction level
No errors

Checking the households Estimates table at the jurisdiction level
No errors

Checking the housing Estimates table at the jurisdiction level
Errors have occurred on the following rows:
Output is too large to print, see output file.

Checking the population Estimates table at the jurisdiction level
No errors

Checking the sex Estimates table at the jurisdiction level
No errors

Checking the age_ethnicity Estimates table at the jurisdiction level
Errors have occurred on the following rows:
Output is too large to print, see output file.

Checking the age_sex_ethnicity Estimates table at the jurisdiction level
No errors

### Run Check 4

In [ ]:
# Run checks that year over year Estimates values do not change by too much
# This check should only be run at the region level to prevent small populations with high 
# variability from distorting results
if("region" in GEOGRAPHIES):
    pc.ThresholdAnalysis().check_thresholds(
        p_threshold=5,
        n_threshold=500,
        vintage=NEW_VINTAGE, 
        geo_list=["region"],
        est_table_list=EST_TABLES,
        raw_folder=RAW_FOLDER, 
        save=True,
        save_location=OUTPUTS_FOLDER)
else:
    print("This check should only be run at the region level.")

Running check 4: Threshold Analysis
Checking file QA_2021_01_region_age.
Errors have occurred on the following rows:
       region  yr_id  Under 5  5 to 9  10 to 14  15 to 17  18 and 19  \
0   San Diego   2010   203423  194029    198716    128000      97095
1   San Diego   2011   209939  197889    198979    128906      96042
2   San Diego   2012   215677  203754    198403    131596      97211
3   San Diego   2013   219753  210910    199295    133282      98736
4   San Diego   2014   222064  216798    200875    132669     100101
5   San Diego   2015   223794  221228    202767    131345     101507
6   San Diego   2016   223203  224837    205110    130974      99967
7   San Diego   2017   221450  227947    209845    131182      98214
8   San Diego   2018   218753  229178    215375    131475      98417
9   San Diego   2019   213481  230127    220121    132226      99228
10  San Diego   2020   205904  230989    223104    133490      98931

    20 to 24  25 to 29  30 to 34  35 to 39  40 to 44  45 to 49  50 to 54  \
0     270750    250737    220185    211012    209551    219795    210980
1     270069    246734    224967    209228    211981    217105    213349
2     267545    240615    230265    207600    213448    213155    215234
3     265080    234627    235654    208516    213747    210161    216585
4     263770    228231    240016    210707    212562    208012    217419
5     263863    222366    240769    214765    210549    208039    216913
6     263800    218225    236041    219706    207340    209300    213495
7     264492    215556    229923    224662    205455    210778    209297
8     264398    212399    223371    229237    205466    210640    205491
9     263346    209843    216141    232640    206688    208761    202413
10    261861    207190    208315    231394    208834    204996    200622

    55 to 59  60 and 61  62 to 64  65 to 69  70 to 74  75 to 79  80 to 84  \
0     180305      64088     85223    103241     77313     64347     52564
1     185353      65439     90154    108268     80121     64799     53080
2     191186      66248     94222    116570     83765     65707     53304
3     196575      68049     96238    125993     88669     67357     53490
4     200838      71049     97916    134674     93526     69690     53723
5     204854      74309     99930    143484     98089     72590     54010
6     207652      76640    102785    150715    103069     75194     54249
7     209349      78005    107057    155001    110500     78005     55108
8     210030      78984    110938    157747    119116     81643     56539
9     209873      79805    113581    161305    126877     85459     58454
10    207276      80734    114670    164902    134013     88881     60482

    85 and Older
0          53960
1          55202
2          56304
3          57184
4          58123
5          59536
6          60708
7          61541
8          61921
9          62950
10         64691
       region  yr_id   Under 5    5 to 9  10 to 14  15 to 17  18 and 19  \
0   San Diego   2010       NaN       NaN       NaN       NaN        NaN
1   San Diego   2011  3.203178  1.989393  0.132350  0.707813  -1.084505
2   San Diego   2012  2.733175  2.963783 -0.289478  2.086792   1.217176
3   San Diego   2013  1.889863  3.512078  0.449590  1.281194   1.568753
4   San Diego   2014  1.051635  2.791712  0.792795 -0.459927   1.382474
5   San Diego   2015  0.779055  2.043377  0.941879 -0.997972   1.404581
6   San Diego   2016 -0.264082  1.631349  1.155513 -0.282462  -1.517137
7   San Diego   2017 -0.785384  1.383224  2.308517  0.158810  -1.753579
8   San Diego   2018 -1.217882  0.540038  2.635278  0.223354   0.206692
9   San Diego   2019 -2.410024  0.414089  2.203598  0.571211   0.824045
10  San Diego   2020 -3.549262  0.374576  1.355164  0.955939  -0.299311

    20 to 24  25 to 29  30 to 34  35 to 39  40 to 44  45 to 49  50 to 54  \
0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
1  -0.251524 -1.596494  2.171810 -0.845450  1.159622 -1.223868  1.122855
2  -0.934576 -2.479999  2.355012 -0.778099  0.692043 -1.819396  0.883529
3  -0.921340 -2.488623  2.340347  0.441233  0.140081 -1.404612  0.627689
4  -0.494190 -2.726029  1.851019  1.050759 -0.554394 -1.022549  0.385068
5   0.035258 -2.569765  0.313729  1.925897 -0.947018  0.012980 -0.232730
6  -0.023876 -1.862245 -1.963708  2.300654 -1.524111  0.606136 -1.575747
7   0.262320 -1.223050 -2.591923  2.255742 -0.909135  0.706163 -1.966322
8  -0.035540 -1.464585 -2.849650  2.036392  0.005354 -0.065472 -1.818468
9  -0.397885 -1.203395 -3.236768  1.484490  0.594746 -0.892043 -1.497876
10 -0.563897 -1.264279 -3.620785 -0.535591  1.038280 -1.803498 -0.884825

    55 to 59  60 and 61  62 to 64  65 to 69  70 to 74  75 to 79  80 to 84  \
0        NaN        NaN       NaN       NaN       NaN       NaN       NaN
1   2.799701   2.108039  5.785997  4.869190  3.631989  0.702441  0.981660
2   3.146968   1.236266  4.512279  7.668009  4.548121  1.401256  0.422005
3   2.818721   2.718573  2.139628  8.083555  5.854474  2.511148  0.348942
4   2.168638   4.408588  1.743594  6.890065  5.477675  3.463634  0.435595
5   1.999622   4.588383  2.056865  6.541723  4.878857  4.161286  0.534222
6   1.365851   3.136901  2.857000  5.039586  5.077022  3.587271  0.442511
7   0.817233   1.781054  4.156248  2.843778  7.209733  3.738330  1.583439
8   0.325294   1.255048  3.625172  1.771601  7.797285  4.663804  2.596719
9  -0.074751   1.039451  2.382412  2.255510  6.515497  4.674008  3.387043
10 -1.237415   1.164087  0.958787  2.229937  5.624345  4.004259  3.469395

    85 and Older
0            NaN
1       2.301705
2       1.996304
3       1.562944
4       1.642068
5       2.431051
6       1.968557
7       1.372142
8       0.617475
9       1.661795
10      2.765687
       region  yr_id  Under 5  5 to 9  10 to 14  15 to 17  18 and 19  \
0   San Diego   2010      NaN     NaN       NaN       NaN        NaN
1   San Diego   2011   6516.0  3860.0     263.0     906.0    -1053.0
2   San Diego   2012   5738.0  5865.0    -576.0    2690.0     1169.0
3   San Diego   2013   4076.0  7156.0     892.0    1686.0     1525.0
4   San Diego   2014   2311.0  5888.0    1580.0    -613.0     1365.0
5   San Diego   2015   1730.0  4430.0    1892.0   -1324.0     1406.0
6   San Diego   2016   -591.0  3609.0    2343.0    -371.0    -1540.0
7   San Diego   2017  -1753.0  3110.0    4735.0     208.0    -1753.0
8   San Diego   2018  -2697.0  1231.0    5530.0     293.0      203.0
9   San Diego   2019  -5272.0   949.0    4746.0     751.0      811.0
10  San Diego   2020  -7577.0   862.0    2983.0    1264.0     -297.0

    20 to 24  25 to 29  30 to 34  35 to 39  40 to 44  45 to 49  50 to 54  \
0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
1     -681.0   -4003.0    4782.0   -1784.0    2430.0   -2690.0    2369.0
2    -2524.0   -6119.0    5298.0   -1628.0    1467.0   -3950.0    1885.0
3    -2465.0   -5988.0    5389.0     916.0     299.0   -2994.0    1351.0
4    -1310.0   -6396.0    4362.0    2191.0   -1185.0   -2149.0     834.0
5       93.0   -5865.0     753.0    4058.0   -2013.0      27.0    -506.0
6      -63.0   -4141.0   -4728.0    4941.0   -3209.0    1261.0   -3418.0
7      692.0   -2669.0   -6118.0    4956.0   -1885.0    1478.0   -4198.0
8      -94.0   -3157.0   -6552.0    4575.0      11.0    -138.0   -3806.0
9    -1052.0   -2556.0   -7230.0    3403.0    1222.0   -1879.0   -3078.0
10   -1485.0   -2653.0   -7826.0   -1246.0    2146.0   -3765.0   -1791.0

    55 to 59  60 and 61  62 to 64  65 to 69  70 to 74  75 to 79  80 to 84  \
0        NaN        NaN       NaN       NaN       NaN       NaN       NaN
1     5048.0     1351.0    4931.0    5027.0    2808.0     452.0     516.0
2     5833.0      809.0    4068.0    8302.0    3644.0     908.0     224.0
3     5389.0     1801.0    2016.0    9423.0    4904.0    1650.0     186.0
4     4263.0     3000.0    1678.0    8681.0    4857.0    2333.0     233.0
5     4016.0     3260.0    2014.0    8810.0    4563.0    2900.0     287.0
6     2798.0     2331.0    2855.0    7231.0    4980.0    2604.0     239.0
7     1697.0     1365.0    4272.0    4286.0    7431.0    2811.0     859.0
8      681.0      979.0    3881.0    2746.0    8616.0    3638.0    1431.0
9     -157.0      821.0    2643.0    3558.0    7761.0    3816.0    1915.0
10   -2597.0      929.0    1089.0    3597.0    7136.0    3422.0    2028.0

    85 and Older
0            NaN
1         1242.0
2         1102.0
3          880.0
4          939.0
5         1413.0
6         1172.0
7          833.0
8          380.0
9         1029.0
10        1741.0

Checking file QA_2021_01_region_ethnicity.
No errors

Checking file QA_2021_01_region_household_income.
Errors have occurred on the following rows:
       region  yr_id  Less than $15,000  $15,000 to $29,999  \
1   San Diego   2011             117655              149507
2   San Diego   2012             134337              155257
3   San Diego   2013             131072              160093
4   San Diego   2014             128320              158893
5   San Diego   2015             124626              150080
6   San Diego   2016             115110              147323
7   San Diego   2017             105079              145561
8   San Diego   2018             100413              141203
9   San Diego   2019             105174              136187
10  San Diego   2020             102652              125813

    $30,000 to $44,999  $45,000 to $59,999  $60,000 to $74,999  \
1               153501              124115              111644
2               146891              127719              109220
3               151607              127953              106486
4               152621              130246              104963
5               148524              125962              105111
6               144357              132673              110314
7               145220              128290              111683
8               136210              127594              111101
9               137874              127806              107921
10              132953              124422              111506

    $75,000 to $99,999  $100,000 to $124,999  $125,000 to $149,999  \
1               142889                100770                 63130
2               138667                 97433                 59492
3               138387                 94533                 59892
4               136209                 98783                 58638
5               145658                104344                 60748
6               150925                107191                 62794
7               148071                110661                 65851
8               152554                114247                 68256
9               154683                115043                 70938
10              160243                122344                 68015

    $150,000 to $199,999  $200,000 or more
1                  64158             62052
2                  63596             60900
3                  68119             63211
4                  66331             72559
5                  69260             80597
6                  69222             81334
7                  78144             90905
8                  83083            103130
9                  87781            103869
10                 88224            117809
       region  yr_id  Less than $15,000  $15,000 to $29,999  \
1   San Diego   2011           0.218060            0.300552
2   San Diego   2012          14.178743            3.845974
3   San Diego   2013          -2.430455            3.114835
4   San Diego   2014          -2.099609           -0.749564
5   San Diego   2015          -2.878741           -5.546500
6   San Diego   2016          -7.635646           -1.837020
7   San Diego   2017          -8.714273           -1.196011
8   San Diego   2018          -4.440469           -2.993934
9   San Diego   2019           4.741418           -3.552332
10  San Diego   2020          -2.397931           -7.617467

    $30,000 to $44,999  $45,000 to $59,999  $60,000 to $74,999  \
1             0.320238            0.299813            0.270336
2            -4.306161            2.903759           -2.171187
3             3.210544            0.183215           -2.503205
4             0.668835            1.792064           -1.430235
5            -2.684427           -3.289161            0.141002
6            -2.805607            5.327797            4.950005
7             0.597823           -3.303611            1.241003
8            -6.204380           -0.542521           -0.521118
9             1.221643            0.166152           -2.862260
10           -3.569201           -2.647763            3.321874

    $75,000 to $99,999  $100,000 to $124,999  $125,000 to $149,999  \
1             0.175970              0.170978              0.169779
2            -2.954741             -3.311501             -5.762712
3            -0.201923             -2.976404              0.672359
4            -1.573847              4.495785             -2.093769
5             6.937133              5.629511              3.598349
6             3.616005              2.728475              3.368012
7            -1.891005              3.237212              4.868300
8             3.027602              3.240527              3.652184
9             1.395571              0.696736              3.929325
10            3.594448              6.346323             -4.120500

    $150,000 to $199,999  $200,000 or more
1               0.143602          0.108091
2              -0.875962         -1.856507
3               7.112083          3.794745
4              -2.624818         14.788565
5               4.415733         11.077881
6              -0.054866          0.914426
7              12.888966         11.767526
8               6.320383         13.448105
9               5.654586          0.716571
10              0.504665         13.420751
       region  yr_id  Less than $15,000  $15,000 to $29,999  \
1   San Diego   2011              256.0               448.0
2   San Diego   2012            16682.0              5750.0
3   San Diego   2013            -3265.0              4836.0
4   San Diego   2014            -2752.0             -1200.0
5   San Diego   2015            -3694.0             -8813.0
6   San Diego   2016            -9516.0             -2757.0
7   San Diego   2017           -10031.0             -1762.0
8   San Diego   2018            -4666.0             -4358.0
9   San Diego   2019             4761.0             -5016.0
10  San Diego   2020            -2522.0            -10374.0

    $30,000 to $44,999  $45,000 to $59,999  $60,000 to $74,999  \
1                490.0               371.0               301.0
2              -6610.0              3604.0             -2424.0
3               4716.0               234.0             -2734.0
4               1014.0              2293.0             -1523.0
5              -4097.0             -4284.0               148.0
6              -4167.0              6711.0              5203.0
7                863.0             -4383.0              1369.0
8              -9010.0              -696.0              -582.0
9               1664.0               212.0             -3180.0
10             -4921.0             -3384.0              3585.0

    $75,000 to $99,999  $100,000 to $124,999  $125,000 to $149,999  \
1                251.0                 172.0                 107.0
2              -4222.0               -3337.0               -3638.0
3               -280.0               -2900.0                 400.0
4              -2178.0                4250.0               -1254.0
5               9449.0                5561.0                2110.0
6               5267.0                2847.0                2046.0
7              -2854.0                3470.0                3057.0
8               4483.0                3586.0                2405.0
9               2129.0                 796.0                2682.0
10              5560.0                7301.0               -2923.0

    $150,000 to $199,999  $200,000 or more
1                   92.0              67.0
2                 -562.0           -1152.0
3                 4523.0            2311.0
4                -1788.0            9348.0
5                 2929.0            8038.0
6                  -38.0             737.0
7                 8922.0            9571.0
8                 4939.0           12225.0
9                 4698.0             739.0
10                 443.0           13940.0

Checking file QA_2021_01_region_households.
No errors

Checking file QA_2021_01_region_housing.
Errors have occurred on the following rows:
       region  yr_id  Mobile Home  Multifamily  Single Family - Detached  \
2   San Diego   2012        42666       414893                    592312
3   San Diego   2013        42502       416458                    593807
9   San Diego   2019        41947       439484                    607738
10  San Diego   2020        42030       446279                    611331

    Single Family - Multiple Unit  Single-family Attached  \
2                          112461                       0
3                          112736                       0
9                          115649                       0
10                         116403                       0

    Single-family Detached    units  unoccupiable  occupied  vacancy
2                        0  1162332         40227   1093512    68820
3                        0  1165503         40187   1101353    64150
9                        0  1204818         39696   1147276    57542
10                       0  1216043         39632   1153981    62062
       region  yr_id  Mobile Home  Multifamily  Single Family - Detached  \
2   San Diego   2012    -0.077285     0.345617                  0.359545
3   San Diego   2013    -0.384381     0.377206                  0.252401
9   San Diego   2019    -0.030982     0.946335                  0.418868
10  San Diego   2020     0.197869     1.546131                  0.591209

    Single Family - Multiple Unit  Single-family Attached  \
2                        0.347994                     NaN
3                        0.244529                     NaN
9                        0.405445                     NaN
10                       0.651973                     NaN

    Single-family Detached     units  unoccupiable  occupied   vacancy
2                      NaN  0.337355     -0.067074  0.375521 -0.265206
3                      NaN  0.272814     -0.099436  0.717047 -6.785818
9                      NaN  0.593550     -0.281350  0.833633 -3.965419
10                     NaN  0.931676     -0.161225  0.584428  7.855132
       region  yr_id  Mobile Home  Multifamily  Single Family - Detached  \
2   San Diego   2012        -33.0       1429.0                    2122.0
3   San Diego   2013       -164.0       1565.0                    1495.0
9   San Diego   2019        -13.0       4120.0                    2535.0
10  San Diego   2020         83.0       6795.0                    3593.0

    Single Family - Multiple Unit  Single-family Attached  \
2                           390.0                     0.0
3                           275.0                     0.0
9                           467.0                     0.0
10                          754.0                     0.0

    Single-family Detached    units  unoccupiable  occupied  vacancy
2                      0.0   3908.0         -27.0    4091.0   -183.0
3                      0.0   3171.0         -40.0    7841.0  -4670.0
9                      0.0   7109.0        -112.0    9485.0  -2376.0
10                     0.0  11225.0         -64.0    6705.0   4520.0

Checking file QA_2021_01_region_population.
Errors have occurred on the following rows:
       region  yr_id  Group Quarters - College  Group Quarters - Military  \
0   San Diego   2010                     16055                      43597
1   San Diego   2011                     16968                      42309

In [ ]:
# Run checks that year over year age_sex and age_sex_ethnicity Estimates values do not change by 
# too much
# Similar to the previous notebook cell, this check should only be run at the region level. Still,
# breaking down into age/sex/ethnicity or just age/ethnicity will greater lower populations and 
# increase volatility. As such, the threshold has been increased from 5 to 10
if("region" in GEOGRAPHIES):
    pc.ThresholdAnalysis().check_thresholds(
        p_threshold=5,
        n_threshold=500,
        vintage=NEW_VINTAGE, 
        geo_list=["region"],
        est_table_list=AGE_SEX_ETHNICITY,
        raw_folder=RAW_FOLDER, 
        save=True,
        save_location=OUTPUTS_FOLDER)
else:
    print("This check should only be run at the region level.")

Running check 4: Threshold Analysis
Checking file QA_2021_01_region_age_ethnicity.
Errors have occurred on the following rows:
        region  yr_id       name  Hispanic  \
12   San Diego   2010   15 to 17     57838
13   San Diego   2011   15 to 17     53190
24   San Diego   2010  18 and 19     39688
25   San Diego   2011  18 and 19     33682
36   San Diego   2010   20 to 24     93539
..         ...    ...        ...       ...
232  San Diego   2014    Under 5    100513
233  San Diego   2015    Under 5    101399
237  San Diego   2019    Under 5     92535
238  San Diego   2020    Under 5     86555
239  San Diego   2021    Under 5     81111

     Non-Hispanic, American Indian or Alaska Native  Non-Hispanic, Asian  \
12                                              605                11065
13                                              642                12987
24                                              501                 9922
25                                              552                 9256
36                                             1496                29194
..                                              ...                  ...
232                                            1039                18801
233                                            1013                19113
237                                             915                18604
238                                             927                18097
239                                             943                17481

     Non-Hispanic, Black  Non-Hispanic, Hawaiian or Pacific Islander  \
12                  6966                                         579
13                  6502                                         622
24                  5149                                         472
25                  5879                                         484
36                 14878                                        1439
..                   ...                                         ...
232                10125                                         809
233                 9987                                         835
237                 9465                                         763
238                 9543                                         729
239                 9487                                         692

     Non-Hispanic, Other  Non-Hispanic, Two or More Races  Non-Hispanic, White
12                   344                             5911                44692
13                   349                             5322                49292
24                   223                             3879                37261
25                   249                             3727                42213
36                   615                             9718               119871
..                   ...                              ...                  ...
232                  538                            10780                79459
233                  547                             9951                80949
237                  487                             9595                81117
238                  461                             9672                79920
239                  494                             9790                77648

[80 rows x 11 columns]
        region       name  yr_id   Hispanic  \
12   San Diego   15 to 17   2010        NaN
13   San Diego   15 to 17   2011  -8.036239
24   San Diego  18 and 19   2010        NaN
25   San Diego  18 and 19   2011 -15.133038
36   San Diego   20 to 24   2010        NaN
..         ...        ...    ...        ...
232  San Diego    Under 5   2014   1.148211
233  San Diego    Under 5   2015   0.881478
237  San Diego    Under 5   2019  -4.511542
238  San Diego    Under 5   2020  -6.462420
239  San Diego    Under 5   2021  -6.289642

     Non-Hispanic, American Indian or Alaska Native  Non-Hispanic, Asian  \
12                                              NaN                  NaN
13                                         6.115702            17.370086
24                                              NaN                  NaN
25                                        10.179641            -6.712356
36                                              NaN                  NaN
..                                              ...                  ...
232                                        1.168452             1.863792
233                                       -2.502406             1.659486
237                                       -0.543478            -1.664993
238                                        1.311475            -2.725220
239                                        1.725998            -3.403879

     Non-Hispanic, Black  Non-Hispanic, Hawaiian or Pacific Islander  \
12                   NaN                                         NaN
13             -6.660924                                    7.426598
24                   NaN                                         NaN
25             14.177510                                    2.542373
36                   NaN                                         NaN
..                   ...                                         ...
232            -1.045739                                    0.000000
233            -1.362963                                    3.213844
237             0.392448                                   -3.661616
238             0.824089                                   -4.456094
239            -0.586818                                   -5.075446

     Non-Hispanic, Other  Non-Hispanic, Two or More Races  Non-Hispanic, White
12                   NaN                              NaN                  NaN
13              1.453488                        -9.964473            10.292670
24                   NaN                              NaN                  NaN
25             11.659193                        -3.918536            13.290035
36                   NaN                              NaN                  NaN
..                   ...                              ...                  ...
232             1.318267                        -7.839617             2.358685
233             1.672862                        -7.690167             1.875181
237            -3.944773                         0.366109            -0.737885
238            -5.338809                         0.802501            -1.475646
239             7.158351                         1.220017            -2.842843

[80 rows x 11 columns]
        region       name  yr_id  Hispanic  \
12   San Diego   15 to 17   2010       NaN
13   San Diego   15 to 17   2011   -4648.0
24   San Diego  18 and 19   2010       NaN
25   San Diego  18 and 19   2011   -6006.0
36   San Diego   20 to 24   2010       NaN
..         ...        ...    ...       ...
232  San Diego    Under 5   2014    1141.0
233  San Diego    Under 5   2015     886.0
237  San Diego    Under 5   2019   -4372.0
238  San Diego    Under 5   2020   -5980.0
239  San Diego    Under 5   2021   -5444.0

     Non-Hispanic, American Indian or Alaska Native  Non-Hispanic, Asian  \
12                                              NaN                  NaN
13                                             37.0               1922.0
24                                              NaN                  NaN
25                                             51.0               -666.0
36                                              NaN                  NaN
..                                              ...                  ...
232                                            12.0                344.0
233                                           -26.0                312.0
237                                            -5.0               -315.0
238                                            12.0               -507.0
239                                            16.0               -616.0

     Non-Hispanic, Black  Non-Hispanic, Hawaiian or Pacific Islander  \
12                   NaN                                         NaN
13                -464.0                                        43.0
24                   NaN                                         NaN
25                 730.0                                        12.0
36                   NaN                                         NaN
..                   ...                                         ...
232               -107.0                                         0.0
233               -138.0                                        26.0
237                 37.0                                       -29.0
238                 78.0                                       -34.0
239                -56.0                                       -37.0

     Non-Hispanic, Other  Non-Hispanic, Two or More Races  Non-Hispanic, White
12                   NaN                              NaN                  NaN
13                   5.0                           -589.0               4600.0
24                   NaN                              NaN                  NaN
25                  26.0                           -152.0               4952.0
36                   NaN                              NaN                  NaN
..                   ...                              ...                  ...
232                  7.0                           -917.0               1831.0
233                  9.0                           -829.0               1490.0
237                -20.0                             35.0               -603.0
238                -26.0                             77.0              -1197.0
239                 33.0                            118.0              -2272.0

[80 rows x 11 columns]

Checking file QA_2021_01_region_age_sex_ethnicity.
Errors have occurred on the following rows:
        region  yr_id       name     sex  Hispanic  Non-Hispanic, White  \
12   San Diego   2010   15 to 17  Female     27852                21611
13   San Diego   2011   15 to 17  Female     25595                23538
24   San Diego   2010  18 and 19  Female     18981                16601
25   San Diego   2011  18 and 19  Female     17785                17638
36   San Diego   2010   20 to 24  Female     44143                51140
..         ...    ...        ...     ...       ...                  ...
440  San Diego   2018   75 to 79    Male      5582                25013
441  San Diego   2019   75 to 79    Male      5753                26593
477  San Diego   2019    Under 5    Male     46172                40738
478  San Diego   2020    Under 5    Male     43370                40414
479  San Diego   2021    Under 5    Male     41132                39741

     Non-Hispanic, Asian  Non-Hispanic, Hawaiian or Pacific Islander  \
12                  5315                                         270
13                  6292                                         293
24                  4888                                         204
25                  4837                                         206
36                 14168                                         610
..                   ...                                         ...
440                 3966                                         124
441                 4081                                         116
477                 9316                                         380
478                 9047                                         372
479                 8836                                         358

     Non-Hispanic, American Indian or Alaska Native  Non-Hispanic, Other  \
12                                              291                  156
13                                              319                  161
24                                              216                  103
25                                              239                  116
36                                              681                  233
..                                              ...                  ...
440                                             157                   52
441                                             155                   55
477                                             485                  247
478                                             502                  241
479                                             518                  264

     Non-Hispanic, Two or More Races  Non-Hispanic, Black
12                              2903                 3260
13                              2663                 3052
24                              1846                 2290
25                              1938                 2422
36                              4824                 6310
..                               ...                  ...
440                              454                 1223
441                              486                 1254
477                             4839                 4742
478                             4901                 4795
479                             5016                 4830

[122 rows x 12 columns]
        region     sex       name  yr_id  Hispanic  Non-Hispanic, White  \
12   San Diego  Female   15 to 17   2010       NaN                  NaN
13   San Diego  Female   15 to 17   2011 -8.103547             8.916755
24   San Diego  Female  18 and 19   2010       NaN                  NaN
25   San Diego  Female  18 and 19   2011 -6.301038             6.246612
36   San Diego  Female   20 to 24   2010       NaN                  NaN
..         ...     ...        ...    ...       ...                  ...
440  San Diego    Male   75 to 79   2018  4.025345             6.542574
441  San Diego    Male   75 to 79   2019  3.063418             6.316715
477  San Diego    Male    Under 5   2019 -4.640740            -0.793883
478  San Diego    Male    Under 5   2020 -6.068613            -0.795326
479  San Diego    Male    Under 5   2021 -5.160249            -1.665265

     Non-Hispanic, Asian  Non-Hispanic, Hawaiian or Pacific Islander  \
12                   NaN                                         NaN
13             18.381938                                    8.518519
24                   NaN                                         NaN
25             -1.043372                                    0.980392
36                   NaN                                         NaN
..                   ...                                         ...
440             1.536098                                   -6.060606
441             2.899647                                   -6.451613
477            -2.286553                                   -5.707196
478            -2.887505                                   -2.105263
479            -2.332265                                   -3.763441

     Non-Hispanic, American Indian or Alaska Native  Non-Hispanic, Other  \
12                                              NaN                  NaN
13                                         9.621993             3.205128
24                                              NaN                  NaN
25                                        10.648148            12.621359
36                                              NaN                  NaN
..                                              ...                  ...
440                                       -2.484472             4.000000
441                                       -1.273885             5.769231
477                                        0.622407            -3.515625
478                                        3.505155            -2.429150
479                                        3.187251             9.543568

     Non-Hispanic, Two or More Races  Non-Hispanic, Black
12                               NaN                  NaN
13                         -8.267310            -6.380368
24                               NaN                  NaN
25                          4.983749             5.764192
36                               NaN                  NaN
..                               ...                  ...
440                         7.075472             0.081833
441                         7.048458             2.534751
477                         0.498442            -0.545302
478                         1.281256             1.117672
479                         2.346460             0.729927

[122 rows x 12 columns]
        region     sex       name  yr_id  Hispanic  Non-Hispanic, White  \
12   San Diego  Female   15 to 17   2010       NaN                  NaN
13   San Diego  Female   15 to 17   2011   -2257.0               1927.0
24   San Diego  Female  18 and 19   2010       NaN                  NaN
25   San Diego  Female  18 and 19   2011   -1196.0               1037.0
36   San Diego  Female   20 to 24   2010       NaN                  NaN
..         ...     ...        ...    ...       ...                  ...
440  San Diego    Male   75 to 79   2018     216.0               1536.0
441  San Diego    Male   75 to 79   2019     171.0               1580.0
477  San Diego    Male    Under 5   2019   -2247.0               -326.0
478  San Diego    Male    Under 5   2020   -2802.0               -324.0
479  San Diego    Male    Under 5   2021   -2238.0               -673.0

     Non-Hispanic, Asian  Non-Hispanic, Hawaiian or Pacific Islander  \
12                   NaN                                         NaN
13                 977.0                                        23.0
24                   NaN                                         NaN
25                 -51.0                                         2.0
36                   NaN                                         NaN
..                   ...                                         ...
440                 60.0                                        -8.0
441                115.0                                        -8.0
477               -218.0                                       -23.0
478               -269.0                                        -8.0
479               -211.0                                       -14.0

     Non-Hispanic, American Indian or Alaska Native  Non-Hispanic, Other  \
12                                              NaN                  NaN
13                                             28.0                  5.0
24                                              NaN                  NaN
25                                             23.0                 13.0
36                                              NaN                  NaN
..                                              ...                  ...
440                                            -4.0                  2.0
441                                            -2.0                  3.0
477                                             3.0                 -9.0
478                                            17.0                 -6.0
479                                            16.0                 23.0

     Non-Hispanic, Two or More Races  Non-Hispanic, Black
12                               NaN                  NaN
13                            -240.0               -208.0
24                               NaN                  NaN
25                              92.0                132.0
36                               NaN                  NaN
..                               ...                  ...
440                             30.0                  1.0
441                             32.0                 31.0
477                             24.0                -26.0
478                             62.0                 53.0
479                            115.0                 35.0

[122 rows x 12 columns]

### Run Check 5

In [ ]:
# N/A, done in Power BI

### Run Check 6

In [ ]:
# Run checks that region level Estimates population values are within +/- 1.5% of CA DOF population
# values
pc.DOFPopulation().region_DOF_population_comparison(
    threshold=1.5,
    est_vintage=NEW_VINTAGE, 
    DOF_vintage=DOF_VINTAGE,
    raw_folder=RAW_FOLDER, 
    save=True,
    save_location=OUTPUTS_FOLDER)

Running Check 6: Estimates vs DOF Population Values
No errors

### Run Check 7

In [ ]:
# Run checks that Estimates categorical distributions are within a certain range of CA DOF 
# categorical distributions. For example, is the percent of population in households vs group
# quarters roughly the same between Estimates and CA DOF?
pc.DOFProportion().check_DOF_proportion(
    threshold=1.5,
    est_vintage=NEW_VINTAGE,
    DOF_vintage=DOF_VINTAGE,
    prop_folder=PROP_FOLDER,
    save=True,
    save_location=OUTPUTS_FOLDER)

Running Check 7: DOF Categorical Proportion Check
Checking row_prop files
Errors have occurred on the following rows:
      region  yr_id       name     sex  Hispanic  Non-Hispanic, White  \
2  San Diego   2010   15 to 17  Female  4.222597             3.591888
3  San Diego   2010   15 to 17    Male  4.447925             4.271212
4  San Diego   2010  18 and 19  Female  2.831824             2.734724
5  San Diego   2010  18 and 19    Male  8.626628             8.833974
6  San Diego   2010   20 to 24  Female  3.568784             2.754082
7  San Diego   2010   20 to 24    Male  5.180193             4.725284

   Non-Hispanic, Asian  Non-Hispanic, Hawaiian or Pacific Islander  \
2             1.801953                                    0.047799
3             1.398805                                    0.030476
4             0.067719                                    0.018460
5             0.940497                                    0.044858
6             0.812430                                    0.017953
7             0.238281                                    0.012336

   Non-Hispanic, American Indian or Alaska Native  \
2                                        0.030094
3                                        0.003211
4                                        0.077871
5                                        0.078554
6                                        0.029173
7                                        0.023067

   Non-Hispanic, Two or More Races  Non-Hispanic, Black
2                         0.668915             0.327214
3                         0.673394             0.299005
4                         0.053076             0.280565
5                         0.529163             1.369822
6                         0.081703             0.153964
7                         0.297498             0.221728

Checking col_prop files
No errors

## Runtime

In [ ]:
runtime = time.time() - start
minutes, seconds = divmod(runtime, 60)
print(f'Runtime: {int(minutes)} minutes, {(int(seconds))} seconds')

Runtime: 1 minutes, 45 seconds