In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\ppo\Documents\GQ.csv")
df

,OBJECTID,facilityID,facilityType,name,gqPop,gqMil,gqCiv,gqCivCol,gqOther,comment,effectYear,regionID,subFacility,Check_,FOIAexempt,DOF,DOF_Name,GQRecalc,Shape
0,1,239,301,The Views Senior Living Community,15,0,15,0,15,Bed count found on website,2022,0,23900,5,0,0,NaN,NaN,0xB6080000010C50D4E9658F1C5841001E1FC586833D41
1,2,242,301,Sabre Springs Senior Living,100,0,100,0,100,www.seniorcareauthority.com capacity,2022,0,24200,5,0,0,NaN,NaN,0xB6080000010C60464F900B105841808BC774A6603D41
2,3,280,301,Heritage Hills of Oceanside,64,0,64,0,64,seniorcareauhority.com,2022,0,28000,5,0,0,NaN,NaN,0xB6080000010CC0E59B50FEC5574140F9F28BF7BD3E41
3,4,240,801,"534 Telford Ln, Ramona, CA 92065",1,0,1,0,1,NUCLEUS_US 290 - Rest Home/Convalescent Hospital,2022,0,24000,5,0,0,NaN,NaN,0xB6080000010C000B8AEE375358418028FE6D1EDE3D41
4,5,134,301,Luther Towers,200,0,200,0,200,Retirement Facility src: PARCELS_ALL,2022,0,13400,1,0,0,NaN,NaN,0xB6080000010CC02D57F1C1F55741C03B1CE3DA1F3C41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,923,287,405,Villa de Vida,54,0,54,0,54,Count from PARCELS_ALL,2022,0,28700,5,0,0,NaN,NaN,0xB6080000010CE02516F135145841806AB99774643D41
923,924,288,301,Encinitas Senior Living,93,0,93,0,93,Count from PARCELS_ALL,2022,0,28800,5,0,0,NaN,NaN,0xB6080000010C8077EAFFA8DA5741402598017FCE3D41
924,925,291,301,Ridgeview Health Center,210,0,210,0,210,online,2022,0,29100,1,0,0,NaN,NaN,0xB6080000010C301A09149C0C5841405D1D06AD1F3D41
925,926,289,801,Glen at Scripps Ranch,400,0,400,0,400,Count from PARCELS_ALL,2022,0,28900,5,0,0,NaN,NaN,0xB6080000010C905B31278D0C58418031919CE71C3D41
926,927,290,801,Protea Senior Living Oceanside,235,0,235,0,235,Count from PARCELS_ALL,2022,0,29000,5,0,0,NaN,NaN,0xB6080000010C8030421177D757418075786587993E41

In [3]:
df["facilityID"].count()

927

In [4]:
df['facilityType'].value_counts()

0      498
301    114
601     66
904     62
501     43
802     33
801     23
202     12
402     11
104     10
201      9
901      8
401      5
602      5
103      5
701      4
101      3
403      3
404      3
203      2
106      2
105      2
405      2
700      1
706      1
Name: facilityType, dtype: int64

In [5]:
df['facilityType'].value_counts().index.sort_values()

Int64Index([  0, 101, 103, 104, 105, 106, 201, 202, 203, 301, 401, 402, 403,
            404, 405, 501, 601, 602, 700, 701, 706, 801, 802, 901, 904],
           dtype='int64')

In [6]:
df.dtypes

OBJECTID          int64
facilityID        int64
facilityType      int64
name             object
gqPop             int64
gqMil             int64
gqCiv             int64
gqCivCol          int64
gqOther           int64
comment          object
effectYear        int64
regionID          int64
subFacility       int64
Check_            int64
FOIAexempt        int64
DOF               int64
DOF_Name         object
GQRecalc        float64
Shape            object
dtype: object

In [7]:
df['effectYear'].value_counts()

2022    927
Name: effectYear, dtype: int64

In [8]:
df['regionID'].value_counts()

0    927
Name: regionID, dtype: int64

In [9]:
df['facilityID']

0      239
1      242
2      280
3      240
4      134
      ...
922    287
923    288
924    291
925    289
926    290
Name: facilityID, Length: 927, dtype: int64

In [10]:
df['subFacility']

0      23900
1      24200
2      28000
3      24000
4      13400
       ...
922    28700
923    28800
924    29100
925    28900
926    29000
Name: subFacility, Length: 927, dtype: int64

In [11]:
df['FOIAexempt'].value_counts()

0    920
6      7
Name: FOIAexempt, dtype: int64

In [12]:
df['DOF'].value_counts()

0    791
1    136
Name: DOF, dtype: int64

In [13]:
df

,OBJECTID,facilityID,facilityType,name,gqPop,gqMil,gqCiv,gqCivCol,gqOther,comment,effectYear,regionID,subFacility,Check_,FOIAexempt,DOF,DOF_Name,GQRecalc,Shape
0,1,239,301,The Views Senior Living Community,15,0,15,0,15,Bed count found on website,2022,0,23900,5,0,0,NaN,NaN,0xB6080000010C50D4E9658F1C5841001E1FC586833D41
1,2,242,301,Sabre Springs Senior Living,100,0,100,0,100,www.seniorcareauthority.com capacity,2022,0,24200,5,0,0,NaN,NaN,0xB6080000010C60464F900B105841808BC774A6603D41
2,3,280,301,Heritage Hills of Oceanside,64,0,64,0,64,seniorcareauhority.com,2022,0,28000,5,0,0,NaN,NaN,0xB6080000010CC0E59B50FEC5574140F9F28BF7BD3E41
3,4,240,801,"534 Telford Ln, Ramona, CA 92065",1,0,1,0,1,NUCLEUS_US 290 - Rest Home/Convalescent Hospital,2022,0,24000,5,0,0,NaN,NaN,0xB6080000010C000B8AEE375358418028FE6D1EDE3D41
4,5,134,301,Luther Towers,200,0,200,0,200,Retirement Facility src: PARCELS_ALL,2022,0,13400,1,0,0,NaN,NaN,0xB6080000010CC02D57F1C1F55741C03B1CE3DA1F3C41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,923,287,405,Villa de Vida,54,0,54,0,54,Count from PARCELS_ALL,2022,0,28700,5,0,0,NaN,NaN,0xB6080000010CE02516F135145841806AB99774643D41
923,924,288,301,Encinitas Senior Living,93,0,93,0,93,Count from PARCELS_ALL,2022,0,28800,5,0,0,NaN,NaN,0xB6080000010C8077EAFFA8DA5741402598017FCE3D41
924,925,291,301,Ridgeview Health Center,210,0,210,0,210,online,2022,0,29100,1,0,0,NaN,NaN,0xB6080000010C301A09149C0C5841405D1D06AD1F3D41
925,926,289,801,Glen at Scripps Ranch,400,0,400,0,400,Count from PARCELS_ALL,2022,0,28900,5,0,0,NaN,NaN,0xB6080000010C905B31278D0C58418031919CE71C3D41
926,927,290,801,Protea Senior Living Oceanside,235,0,235,0,235,Count from PARCELS_ALL,2022,0,29000,5,0,0,NaN,NaN,0xB6080000010C8030421177D757418075786587993E41

In [14]:
(df['gqMil'] + df['gqCiv'])[47]

291

In [15]:
df['gqPop'][47]

292

In [16]:
(df['gqMil'] + df['gqCiv'] == df['gqPop']).sum()

925

In [17]:
np.where((df['gqMil'] + df['gqCiv'] != df['gqPop']))

(array([ 47, 806], dtype=int64),)

In [18]:
(df['gqMil'] + df['gqCiv'])[806]

0

In [19]:
df['gqPop'][806]

1

In [20]:
df['facilityID'].nunique()

253

In [21]:
df[df['OBJECTID']==807].T

                                                           806
OBJECTID                                                   807
facilityID                                                 131
facilityType                                               301
name                  9214 Harness St, Spring Valley, CA 91977
gqPop                                                        1
gqMil                                                        0
gqCiv                                                        0
gqCivCol                                                     0
gqOther                                                      0
comment       ARF for 12 beds.  cannot verfied if it is active
effectYear                                                2022
regionID                                                     0
subFacility                                              13100
Check_                                                       1
FOIAexempt                                                   0
DOF                                                          0
DOF_Name                                                   NaN
GQRecalc                                                   NaN
Shape           0xB6080000010CB08BB4757A26584180992ED14D1C3C41

In [22]:
df[df['OBJECTID']==48].T

                                                          47
OBJECTID                                                  48
facilityID                                                 8
facilityType                                             501
name                                                     USD
gqPop                                                    292
gqMil                                                      0
gqCiv                                                    291
gqCivCol                                                 291
gqOther                                                    0
comment           USD Housing: Manchester Village Apartments
effectYear                                              2022
regionID                                                   0
subFacility                                              808
Check_                                                     1
FOIAexempt                                                 0
DOF                                                        1
DOF_Name                             UNIVERSITY OF SAN DIEGO
GQRecalc                                            0.130267
Shape         0xB6080000010CE0D93CC208F05741C0E247CD9C6E3C41

In [23]:
df['gqCivCol'] + df['gqOther']

0       15
1      100
2       64
3        1
4      200
      ...
922     54
923     93
924    210
925    400
926    235
Length: 927, dtype: int64

In [24]:
df['gqCiv']

0       15
1      100
2       64
3        1
4      200
      ...
922     54
923     93
924    210
925    400
926    235
Name: gqCiv, Length: 927, dtype: int64

In [25]:
((df['gqCivCol'] + df['gqOther'])==df['gqCiv']).sum()

923

In [26]:
np.where((df['gqCivCol'] + df['gqOther'])!=df['gqCiv'])

(array([341, 684, 688, 725], dtype=int64),)

In [27]:
df[df['OBJECTID']==342].T

                                                         341
OBJECTID                                                 342
facilityID                                                62
facilityType                                             301
name                               Villa Monte Vista Nursing
gqPop                                                    149
gqMil                                                      0
gqCiv                                                    149
gqCivCol                                                   0
gqOther                                                   69
comment                                      seniorcenter.us
effectYear                                              2022
regionID                                                   0
subFacility                                             6200
Check_                                                     1
FOIAexempt                                                 0
DOF                                                        0
DOF_Name                                                 NaN
GQRecalc                                                 NaN
Shape         0xB6080000010C50BEB79115175841404C4E3839A53D41

In [28]:
df['subFacility']

0      23900
1      24200
2      28000
3      24000
4      13400
       ...
922    28700
923    28800
924    29100
925    28900
926    29000
Name: subFacility, Length: 927, dtype: int64

In [29]:
df['facilityID']

0      239
1      242
2      280
3      240
4      134
      ...
922    287
923    288
924    291
925    289
926    290
Name: facilityID, Length: 927, dtype: int64

In [30]:
df[df['OBJECTID']==149]

,OBJECTID,facilityID,facilityType,name,gqPop,gqMil,gqCiv,gqCivCol,gqOther,comment,effectYear,regionID,subFacility,Check_,FOIAexempt,DOF,DOF_Name,GQRecalc,Shape
148,149,205,802,The Turning Point Home,20,0,20,0,20,BA 2019 Bed count confirmed by County HHSA web...,2022,0,20500,5,0,0,NaN,NaN,0xB6080000010C0025E34D8FFC574180780502E91D3C41

In [31]:
for index, row in df.iterrows():
    facID = str(row['facilityID'])
    subFacID = str(row['subFacility'])
    length = len(facID)
    if subFacID[:length] != facID:
        print(index, row)
    # print(row['facilityID'])
    # print(row)

915 OBJECTID                                                   916
facilityID                                                 281
facilityType                                               301
name                 Santee Seinor Retirement Commuties Villas
gqPop                                                       12
gqMil                                                        0
gqCiv                                                       12
gqCivCol                                                     0
gqOther                                                     12
comment                                               From DOF
effectYear                                                2022
regionID                                                     0
subFacility                                                  0
Check_                                                       5
FOIAexempt                                                   0
DOF                                                          0
DOF_Name         Santee Seinor Retirement Commuties Villas LLC
GQRecalc                                                   NaN
Shape           0xB6080000010C20B7FD2D0933584100E5C73F9EBC3C41
Name: 915, dtype: object
916 OBJECTID                                                   917
facilityID                                                 282
facilityType                                               301
name                                 Portola Senior Aparments
gqPop                                                      101
gqMil                                                        0
gqCiv                                                      101
gqCivCol                                                     0
gqOther                                                    101
comment                                               From DOF
effectYear                                                2022
regionID                                                     0
subFacility                                                  0
Check_                                                       5
FOIAexempt                                                   0
DOF                                                          0
DOF_Name                                   Shapell Portola LLC
GQRecalc                                                   NaN
Shape           0xB6080000010CB063143D37CD5741800EDE37208A3E41
Name: 916, dtype: object
917 OBJECTID                                                   918
facilityID                                                 283
facilityType                                               301
name                                            Elianna Reuben
gqPop                                                        2
gqMil                                                        0
gqCiv                                                        2
gqCivCol                                                     0
gqOther                                                      2
comment                                               From DOF
effectYear                                                2022
regionID                                                     0
subFacility                                                  0
Check_                                                       5
FOIAexempt                                                   0
DOF                                                          0
DOF_Name                                   Elianna Z C Reuben
GQRecalc                                                   NaN
Shape           0xB6080000010C60B1588C59245841005BE9EA8F7B3C41
Name: 917, dtype: object
918 OBJECTID                                                   919
facilityID                                                 284
facilityType                                               301
name                                          NeuroRestorative
gqPop                                                        6
gqMil                                                        0
gqCiv                                                        6
gqCivCol                                                     0
gqOther                                                      6
comment                                                 Called
effectYear                                                2022
regionID                                                     0
subFacility                                                  0
Check_                                                       5
FOIAexempt                                                   0
DOF                                                          0
DOF_Name                                      NeuroRestorative
GQRecalc                                                   NaN
Shape           0xB6080000010C603EF7B1521E5841C092FD908D753C41
Name: 918, dtype: object