In [1]:
import pandas as pd
import numpy as np

# Doewnload The Data

In [2]:
raw_pums_data = pd.read_csv('PUMSsubset_SanDiego-2017-2021.txt', delimiter='\t')
raw_pums_data

,SERIALNO,SPORDER,PUMA,ST,ADJINC,PWGTP,AGEP,COW,MIL,RELSHIPP,...,WGTP,TYPEHUGQ,HHT,HINCP,Year,Age,NonHispanic,RaceCode,RaceName,Gender
0,2017000000336,1,7307,6,1117630,14,33,1.0,4.0,20,...,14,1,1.0,107000.0,2017,33,1,1,White_NH,M
1,2017000000336,2,7307,6,1117630,12,30,2.0,4.0,21,...,14,1,1.0,107000.0,2017,30,1,1,White_NH,F
2,2017000000634,1,7301,6,1117630,25,63,2.0,4.0,20,...,25,1,1.0,146310.0,2017,63,1,1,White_NH,F
3,2017000000634,2,7301,6,1117630,24,69,1.0,4.0,21,...,25,1,1.0,146310.0,2017,69,1,1,White_NH,M
4,2017000000634,3,7301,6,1117630,39,27,1.0,4.0,25,...,25,1,1.0,146310.0,2017,27,1,1,White_NH,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143742,2021HU1415442,1,7312,6,1029928,16,62,1.0,4.0,20,...,16,1,4.0,100100.0,2021,62,1,1,White_NH,M
143743,2021HU1415478,1,7321,6,1029928,8,76,6.0,4.0,20,...,9,1,6.0,90000.0,2021,76,1,1,White_NH,F
143744,2021HU1415547,1,7315,6,1029928,27,54,1.0,4.0,20,...,27,1,1.0,42000.0,2021,54,1,1,White_NH,M
143745,2021HU1415547,2,7315,6,1029928,21,59,6.0,4.0,21,...,27,1,1.0,42000.0,2021,59,1,1,White_NH,F
143746,2021HU1415547,3,7315,6,1029928,32,18,1.0,4.0,25,...,27,1,1.0,42000.0,2021,18,1,1,White_NH,F